import Link from "next/link";
import { Logo } from "@/components/Logo";

export const metadata = { title: "TekScribe Terms of Service" };

export default function TermsPage() {
  return (
    <div className="min-h-full">
      <header className="border-b border-border bg-surface">
        <div className="max-w-2xl mx-auto px-5 h-16 flex items-center">
          <Link href="/">
            <Logo size={28} />
          </Link>
        </div>
      </header>
      <main className="max-w-2xl mx-auto px-5 py-10 text-[17px] leading-relaxed text-foreground">
        <h1 className="text-2xl font-bold mb-1">Terms of Service</h1>
        <p className="text-[15px] text-muted mb-8">Last updated: June 29, 2026</p>

        <Section title="Acceptance">
          <p>
            By using TekScribe you agree to these terms. If you don&apos;t
            agree, don&apos;t use the service.
          </p>
        </Section>

        <Section title="The service">
          <p>
            TekScribe records voice notes, transcribes and summarizes them with
            AI, and helps you send summaries to your customers by email or text.
          </p>
        </Section>

        <Section title="Your account">
          <p>
            Keep your login secure. You&apos;re responsible for activity under
            your account.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>
            Don&apos;t use TekScribe to record people without the consent
            required by law, to send spam, or for any unlawful purpose. You are
            responsible for the content you record and the messages you send.
          </p>
        </Section>

        <Section title="Verify AI output before you rely on it">
          <p>
            Transcriptions and summaries are generated by AI and may contain
            errors. <strong>Review every summary, parts list, and customer
            message before sending or billing.</strong> You are responsible for
            the accuracy of what you send.
          </p>
        </Section>

        <Section title="Fees">
          <p>
            Paid plans and pricing, where applicable, will be described at
            sign-up. Fees are non-refundable except where required by law.
          </p>
        </Section>

        <Section title="Termination">
          <p>
            You can stop using TekScribe at any time. We may suspend or
            terminate accounts that violate these terms.
          </p>
        </Section>

        <Section title="Disclaimers &amp; liability">
          <p>
            The service is provided &quot;as is,&quot; without warranties. To
            the maximum extent permitted by law, TekScribe is not liable for
            indirect or consequential damages, and our total liability is
            limited to the amount you paid us in the prior 12 months.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions? Email{" "}
            <a href="mailto:support@tekscribe.io" className="text-brand">
              support@tekscribe.io
            </a>
            .
          </p>
        </Section>

        <p className="mt-10 text-[13px] text-muted">
          These terms are a starting point and are not legal advice; have them
          reviewed by a qualified attorney before broad commercial use.
        </p>
      </main>
    </div>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mb-6">
      <h2 className="text-lg font-semibold mb-2">{title}</h2>
      <div className="text-muted">{children}</div>
    </section>
  );
}
